name: "tests"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: ~

env:
    PYTHON_VERSION: 3.13.0
    POETRY_VERSION: 1.8.4

jobs:
  run-django-tests:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - uses: actions/setup-python@v5
      id: setup_python
      name: Set up Python ${{ env.PYTHON_VERSION }}
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - uses: actions/cache@v4
      name: Cache for Poetry setup
      id: poetry_install_cache
      with:
        key: poetry_install-${{ runner.os }}-${{ env.PYTHON_VERSION }}-poetry-${{ env.POETRY_VERSION }}
        path: ${{ env.pythonLocation }}
        restore-keys: |
          poetry_install-${{ runner.os }}-${{ env.PYTHON_VERSION }}-poetry-

    - name: Setup Poetry
      if: steps.poetry_install_cache.outputs.cache-hit != 'true'
      run: pip install poetry==${{ env.POETRY_VERSION }}

    # TODO:
    #   This step must be cached too; but with current small list of packages,
    #   installing them is faster than cache retrieval and update.
    - name: Install packages
      run: poetry install

    - name: Run tests
      working-directory: ./src
      run: poetry run python manage.py test --parallel --shuffle
